spring.application.name=plataforma-servicos
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.packages-to-scan=br.com.ronero.plataformaservicos
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
spring.security.user.name=disabled
spring.security.user.password=disabled
spring.jpa.open-in-view=false